# Generated by Django 5.2.6 on 2025-09-08 11:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.teacherprofile'),
        ),
        migrations.AlterUniqueTogether(
            name='section',
            unique_together={('course', 'section_code', 'semester')},
        ),
    ]
